server:
  port: 8080
  context-path: /demo
spring:
  datasource:
    password: root1234
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_zhuy?useUnicode=true&characterEncoding=UTF-8
    
    


     
